### ISSUE TITLE
I get this error when using nmake and Pretty-Cl ---- NMAKE : fatal error U1077: 

### ISSUE THREAD

**Issue by campanileLabs** [JensWallgren/Pretty-Cl#1]
i get this error NMAKE : fatal error U1077: '"C:\Program Files\CMake\bin\cmake.exe" -E cmake_cl_compile_depends --dep-file=CMakeFiles\paintGL.dir\src\main.cpp.obj.d --working-dir=H:\SoftwareProjects\Image_Editing_Program\Paint_Program\GLFW\PaintGL_0.0.2\build-windows --filter-prefix="Note: including file: " -- Pretty-Cl.exe @C:\Users\satya\AppData\Local\Temp\nm2035.tmp' : return code '0x2'

**Comment by campanileLabs** [comment]
I have set this cmake env 
if(CMAKE_SYSTEM_NAME MATCHES "Windows")
set(CMAKE_C_COMPILER "Pretty-Cl.exe")
set(CMAKE_CXX_COMPILER "Pretty-Cl.exe")
set(CMAKE_CXX_COMPILER_ID MSVC)
set(CMAKE_C_COMPILER_ID MSVC)
set(CMAKE_CXX_FLAGS "${CMAKE_C_FLAGS} /std:c++17 -D __OS_WINDOWS__ -D _WIN32 /Zi /Od /MDd")

...

**Comment by JensWallgren** [comment]
Hey!

The problem stems from this being a Powershell module, that just registers a Powershell function: Pretty-Cl.
That is, it's not an executable. This means that invoking Pretty-Cl**.exe** is not possible.

Not sure if there's a way of running Powershell functions in nmake as the compiler. I don't really have any experience with it. I've always been calling the compiler myself, not going through a build system.
